AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        status:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
    lifecycleCallbacks: {  }
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: articles
            joinColumn:
                name: category_id
                referencedColumnName: id
    
