AppBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        slug:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: 
        preRemove: [removeArticlesFromCategory]
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: category